root: true

extends:
  - airbnb
  - airbnb/hooks
  - airbnb-typescript
  - plugin:react/jsx-runtime
  - plugin:prettier/recommended

env:
  es2022: true
  browser: true

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2022
  project:
    - tsconfig.json

plugins:
  - simple-import-sort

settings:
  import/resolver: typescript

rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '*.js'
        - src/testUtils.tsx
        - src/__mocks__/**
        - '**/__tests__/**/*.ts?(x)'
        - '**/?(*.)+(spec|test).ts?(x)'
  import/order: off
  import/prefer-default-export: off
  jsx-a11y/label-has-associated-control:
    - error
    - assert: either
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  react/jsx-props-no-spreading: off
  react/jsx-sort-props:
    - warn
    - ignoreCase: true
      callbacksLast: true
      shorthandLast: true
      reservedFirst: true
  react/require-default-props:
    - error
    - functions: defaultArguments
  react/prop-types: off
  simple-import-sort/exports: warn
  simple-import-sort/imports: warn
  sort-imports: off

overrides:
  - files:
      - '**/__tests__/**/*.ts?(x)'
      - '**/?(*.)+(spec|test).ts?(x)'
      - jest.setup.js
    extends:
      - plugin:jest/recommended
      - plugin:jest-dom/recommended
      - plugin:testing-library/react
    env:
      jest: true
